### PR TITLE
Compilation fixes for msys2 gcc on windows

### PR DESCRIPTION
**Pull request by AEFeinstein**

### CODE REVIEW

**Comment by AEFeinstein** [comment]
@sellicott and @cnlohr feel free to review!

**Comment by sellicott** [comment]
This looks fine to me, but I will want to test it with clang and tcc before merging.

**Comment by AEFeinstein** [comment]
Please do, and let me know if it passes or fails.

**Comment by sellicott** [comment]
DLLs builds correctly with clang and msys2 on Windows. No issues introduced on Linux. TCC has build issues on windows (for DLL build), ignoring for now.

**Pull request merged**
